### ISSUE TITLE
Fix feature_part_smsg_multiwallet test

### ISSUE THREAD

**Issue by akshaynexus** [ghost-coin/ghost-legacy#21]
Error log:
```34/175 - feature_part_smsg_multiwallet.py failed, Duration: 31 s

stdout:
2020-05-28T19:31:43.697000Z TestFramework (INFO): Initializing test directory /tmp/ghost_test_runner_P_🏃_20200528_222805/feature_part_smsg_multiwallet_141
2020-05-28T19:32:05.268000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_framework.py", line 114, in main
    self.run_test()
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/feature_part_smsg_multiwallet.py", line 82, in run_test
    assert(i < 19)
AssertionError
2020-05-28T19:32:05.320000Z TestFramework (INFO): Stopping nodes
2020-05-28T19:32:14.193000Z TestFramework (WARNING): Not cleaning up dir /tmp/ghost_test_runner_P_🏃_20200528_222805/feature_part_smsg_multiwallet_141
2020-05-28T19:32:14.193000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/ghost_test_runner_P_🏃_20200528_222805/feature_part_smsg_multiwallet_141/test_framework.log
2020-05-28T19:32:14.194000Z TestFramework (ERROR): Hint: Call /home/akshay/Documents/GitRepos/ghost-private/test/functional/combine_logs.py '/tmp/ghost_test_runner_P_🏃_20200528_222805/feature_part_smsg_multiwallet_141' to consolidate all logs


stderr:```

**Comment by akshaynexus** [comment]
Looks like this error doesn't happen anymore on master branch.
