### ISSUE TITLE
Fix the functional test: feature_dbcrash.py

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [ghost-coin/ghost-legacy#3]

**Comment by akshaynexus** [comment]
Error log for ref
```
stdout:
2020-05-21T18:13:24.284000Z TestFramework (INFO): Initializing test directory /tmp/particl_test_runner_P_🏃_20200521_211256/feature_dbcrash_163
2020-05-21T18:13:45.029000Z TestFramework (INFO): Prepped 5001 utxo entries
2020-05-21T18:14:14.724000Z TestFramework (INFO): Iteration 0, generating 2500 transactions [0, 0, 0]
2020-05-21T18:14:26.049000Z TestFramework (INFO): Iteration 1, generating 2500 transactions [0, 0, 0]
2020-05-21T18:16:38.413000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_framework.py", line 114, in main
    self.run_test()
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/feature_dbcrash.py", line 261, in run_test
    self.sync_node3blocks(block_hashes)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/feature_dbcrash.py", line 157, in sync_node3blocks
    nodei_utxo_hash = self.restart_node(i, block_hash)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/feature_dbcrash.py", line 108, in restart_node
    raise AssertionError("Unable to successfully restart node %d in allotted time", node_index)
AssertionError: ('Unable to successfully restart node %d in allotted time', 0)
2020-05-21T18:16:38.468000Z TestFramework (INFO): Stopping nodes
2020-05-21T18:16:38.468000Z TestFramework.node0 (ERROR): Unable to stop node.
Traceback (most recent call last):
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_node.py", line 313, in stop_node
    self.stop(wait=wait)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/authproxy.py", line 142, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/authproxy.py", line 107, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.8/http/client.py", line 1088, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
```

**Comment by akshaynexus** [comment]
Additional error
```
[node 3] Cleaning up leftover process
[node 2] Cleaning up leftover process
[node 1] Cleaning up leftover process
[node 0] Cleaning up leftover process


stderr:
Traceback (most recent call last):
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/feature_dbcrash.py", line 285, in <module>
    ChainstateWriteCrashTest().main()
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_framework.py", line 137, in main
    exit_code = self.shutdown()
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_framework.py", line 248, in shutdown
    self.stop_nodes()
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_framework.py", line 492, in stop_nodes
    node.stop_node(wait=wait)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_node.py", line 327, in stop_node
    raise AssertionError("Unexpected stderr {} != {}".format(stderr, expected_stderr))
AssertionError: Unexpected stderr particld: validation.cpp:2033: DisconnectResult CChainState::DisconnectBlock(const CBlock&, const CBlockIndex*, CCoinsViewCache&): Assertion `pindex->GetBlockHash() == view.GetBestBlock()' failed. !=
```

**Comment by oxarbitrage** [comment]
I dont have a solution but just some comments that might help us advance.

This test is present in bitcoin and it is not failing however ghost is a fork from particle and the test there it is actually failing. 

One option will be to open an issue there and see if they fix it for us.

The test actually fails here: https://github.com/ghost-coin/ghost-private/blob/master/test/functional/test_framework/test_node.py#L227 , the rpc is not coming back after some random number of iterations. I was not able to find the exact cause yet.

**Comment by akshaynexus** [comment]
Not a problem on master atm,closing
