### ISSUE TITLE
Fix the functional test: wallet_bumpfee.py

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [ghost-coin/ghost-legacy#4]

**Comment by akshaynexus** [comment]
Error log for ref
```
135/175 - wallet_bumpfee.py failed, Duration: 66 s                                                                                  

stdout:
2020-05-21T18:31:53.921000Z TestFramework (INFO): Initializing test directory /tmp/particl_test_runner_P_🏃_20200521_211256/wallet_bumpfee_37
2020-05-21T18:32:04.688000Z TestFramework (INFO): Mining blocks...
2020-05-21T18:32:25.290000Z TestFramework (INFO): Running tests
2020-05-21T18:32:25.844000Z TestFramework (INFO): Test simple bumpfee: default
2020-05-21T18:32:31.687000Z TestFramework (INFO): Test simple bumpfee: fee_rate
2020-05-21T18:32:42.741000Z TestFramework (INFO): Test fee_rate args
2020-05-21T18:32:46.201000Z TestFramework (INFO): Test that segwit-sourcing bumpfee works
2020-05-21T18:32:47.412000Z TestFramework (INFO): Test that we cannot replace a non RBF transaction
2020-05-21T18:32:48.062000Z TestFramework (INFO): Test that it cannot bump fee if non-owned inputs are included
2020-05-21T18:32:48.076000Z TestFramework (INFO): Test that fee cannot be bumped when it has descendant
2020-05-21T18:32:48.423000Z TestFramework (INFO): Test that bumped output that is dust is dropped to fee
2020-05-21T18:32:49.086000Z TestFramework (INFO): Test that PSBT is returned for bumpfee in watchonly wallets
2020-05-21T18:32:56.597000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/test_framework.py", line 114, in main
    self.run_test()
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/wallet_bumpfee.py", line 82, in run_test
    test_watchonly_psbt(self, peer_node, rbf_node, dest_address)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/wallet_bumpfee.py", line 363, in test_watchonly_psbt
    psbt = watcher.walletcreatefundedpsbt([], {dest_address: 0.0005}, 0, {"feeRate": 0.00001}, True)['psbt']
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/akshay/Documents/GitRepos/ghost-private/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Signing transaction failed (-4)
2020-05-21T18:32:56.648000Z TestFramework (INFO): Stopping nodes
2020-05-21T18:33:00.359000Z TestFramework (WARNING): Not cleaning up dir /tmp/particl_test_runner_P_🏃_20200521_211256/wallet_bumpfee_37
2020-05-21T18:33:00.359000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/particl_test_runner_P_🏃_20200521_211256/wallet_bumpfee_37/test_framework.log
2020-05-21T18:33:00.359000Z TestFramework (ERROR): Hint: Call /home/akshay/Documents/GitRepos/ghost-private/test/functional/combine_logs.py '/tmp/particl_test_runner_P_🏃_20200521_211256/wallet_bumpfee_37' to consolidate all logs
```

**Comment by akshaynexus** [comment]
this and the keypool tests seems to be failing due to the imported descriptors from initial view,
